title: "My Jekyll Site"
remote_theme: just-the-docs/just-the-docs
search_enabled: true

nav:
  - title: "Home"
    url: "/"
  - title: "Contact"
    url: "/contact"
  - title: "About"
    url: "/about"
